apiVersion: v2
name: tutorial
description: Tutorial helm charts

type: application

version: 0.0.2

appVersion: 0.0.2

# Dependencies
dependencies:
- name: rabbitmq-ha
  version: 1.46.2
  repository: https://kubernetes-charts.storage.googleapis.com
  # import-values:
  #   - child: prometheus.operator
  #     parent: prometheus.operator