apiVersion: v1
kind: Service
metadata:
  name: tutorial-proxy
spec:
  type: {{ .Values.ServiceType }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    proxy: tutorial

{{- if .Values.IngressNginx.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tutorial-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tutorial-proxy
          servicePort: 8080
{{- end }}

{{- if .Values.Istio.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tutorial-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tutorial-virtual-server
spec:
  hosts:
    - "*"
  gateways:
    - tutorial-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /zanudabot
    route:
    - destination:
        host: tutorial-proxy
        port: 
          number: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tutorial-amqp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 31400
      name: amqp
      protocol: HTTP
    hosts:
      - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tutorial-virtual-server-amqp
spec:
  hosts:
    - "*"
  gateways:
    - tutorial-amqp-gateway
  http:
  - match:
    - port: 31400
    route:
    - destination:
        host: tutorial-rabbitmq-ha 
        port: 
          number: 15672

{{- end }}